"use client";
import { useState, useEffect, useRef, useCallback } from "react";
import { Waves, Wind, Bell, Volume2, VolumeX } from "lucide-react";
type SoundKey = "river" | "fan" | "bells" | null;
export function AmbientSound() {
  const [active, setActive] = useState<SoundKey>(null);
  const [open, setOpen] = useState(false);
  const audioCtxRef = useRef<AudioContext | null>(null);
  const nodesRef = useRef<{ master?: GainNode; cleanup?: () => void }>({});
  function getCtx(): AudioContext | null { if (typeof window === "undefined") return null; if (!audioCtxRef.current) { try { const AC = window.AudioContext || (window as any).webkitAudioContext; audioCtxRef.current = new AC(); } catch { return null; } } return audioCtxRef.current; }
  function buildRiver(ctx: AudioContext, master: GainNode) { const bs = 2 * ctx.sampleRate; const buf = ctx.createBuffer(1, bs, ctx.sampleRate); const o = buf.getChannelData(0); let l = 0; for (let i = 0; i < bs; i++) { const w = Math.random() * 2 - 1; o[i] = (l + 0.02 * w) / 1.02; l = o[i]; o[i] *= 3.5; } const n = ctx.createBufferSource(); n.buffer = buf; n.loop = true; const f = ctx.createBiquadFilter(); f.type = "lowpass"; f.frequency.value = 600; const lfo = ctx.createOscillator(); lfo.frequency.value = 0.15; const lg = ctx.createGain(); lg.gain.value = 250; lfo.connect(lg); lg.connect(f.frequency); const rg = ctx.createGain(); rg.gain.value = 0.18; n.connect(f); f.connect(rg); rg.connect(master); n.start(); lfo.start(); return () => { try { n.stop(); lfo.stop(); } catch {} n.disconnect(); f.disconnect(); rg.disconnect(); lfo.disconnect(); lg.disconnect(); }; }
  function buildFan(ctx: AudioContext, master: GainNode) { const osc = ctx.createOscillator(); osc.type = "sawtooth"; osc.frequency.value = 60; const og = ctx.createGain(); og.gain.value = 0.02; const f = ctx.createBiquadFilter(); f.type = "lowpass"; f.frequency.value = 200; const tr = ctx.createOscillator(); tr.frequency.value = 7; const tg = ctx.createGain(); tg.gain.value = 0.4; const to = ctx.createConstantSource(); to.offset.value = 0.6; const fa = ctx.createGain(); fa.gain.value = 0.08; osc.connect(f); f.connect(og); og.connect(fa); tr.connect(tg); tg.connect(fa.gain); to.connect(fa.gain); fa.connect(master); osc.start(); tr.start(); to.start(); return () => { try { osc.stop(); tr.stop(); to.stop(); } catch {} }; }
  function buildBells(ctx: AudioContext, master: GainNode) { let s = false; let t: any; function p() { if (s) return; const n = ctx.currentTime; const f = 220 + Math.random() * 80; [1, 2.4, 3.8, 5.2].forEach((pp, i) => { const o = ctx.createOscillator(); o.type = "sine"; o.frequency.value = f * pp; const g = ctx.createGain(); g.gain.setValueAtTime(0, n); g.gain.linearRampToValueAtTime([0.5, 0.3, 0.2, 0.1][i] * 0.3, n + 0.01); g.gain.exponentialRampToValueAtTime(0.0001, n + 4); o.connect(g); g.connect(master); o.start(n); o.stop(n + 4.5); }); t = setTimeout(p, 15000 + Math.random() * 30000); } t = setTimeout(p, 2000); return () => { s = true; if (t) clearTimeout(t); }; }
  const stopAll = useCallback(() => { if (nodesRef.current.cleanup) { nodesRef.current.cleanup(); nodesRef.current.cleanup = undefined; } if (nodesRef.current.master) { try { nodesRef.current.master.disconnect(); } catch {} nodesRef.current.master = undefined; } }, []);
  const play = useCallback((key: Exclude<SoundKey, null>) => { const ctx = getCtx(); if (!ctx) return; if (ctx.state === "suspended") ctx.resume(); stopAll(); const m = ctx.createGain(); m.gain.value = 0.7; m.connect(ctx.destination); nodesRef.current.master = m; let c: () => void = () => {}; if (key === "river") c = buildRiver(ctx, m); else if (key === "fan") c = buildFan(ctx, m); else if (key === "bells") c = buildBells(ctx, m); nodesRef.current.cleanup = () => { c(); try { m.disconnect(); } catch {} }; setActive(key); }, [stopAll]);
  const stop = useCallback(() => { stopAll(); setActive(null); }, [stopAll]);
  useEffect(() => { return () => { stopAll(); if (audioCtxRef.current) { try { audioCtxRef.current.close(); } catch {} } }; }, [stopAll]);
  const sounds = [{ key: "river" as const, icon: Waves, label: "Río" }, { key: "fan" as const, icon: Wind, label: "Ventilador" }, { key: "bells" as const, icon: Bell, label: "Campanas" }];
  return (<div className="bg-[#FFFBF0]/95 backdrop-blur-md rounded-2xl shadow-lg border border-[var(--fg)]/15 overflow-hidden"><button onClick={() => setOpen(!open)} className="w-full px-5 py-4 flex items-center justify-between gap-3" aria-expanded={open}><div className="flex items-center gap-3"><div className={`w-9 h-9 rounded-full flex items-center justify-center transition-colors ${active ? "bg-[var(--accent)] text-[#FFFBF0]" : "bg-[var(--fg)]/10 text-[var(--accent)]"}`}>{active ? <Volume2 className="w-4 h-4" /> : <VolumeX className="w-4 h-4" />}</div><div className="text-left"><div className="eyebrow text-[var(--fg)]/60">Sonido</div><div className="font-serif text-sm text-[var(--fg)]">{active ? sounds.find(s => s.key === active)?.label : "Apagado"}</div></div></div><span className={`text-[var(--fg)]/60 transition-transform ${open ? "rotate-180" : ""}`}>▾</span></button>{open && (<div className="px-3 pb-3 grid grid-cols-3 gap-2 border-t border-[var(--fg)]/15 pt-3">{sounds.map(s => (<button key={s.key} onClick={() => active === s.key ? stop() : play(s.key)} className={`magnetic-target hover-spring flex flex-col items-center gap-1.5 p-3 rounded-xl transition-all ${active === s.key ? "bg-[var(--accent)] text-[#FFFBF0] shadow-md" : "bg-[var(--fg)]/5 text-[var(--fg)] hover:bg-[var(--golden)]/30"}`}><s.icon className="w-4 h-4" /><span className="text-[10px] font-medium text-center leading-tight">{s.label}</span></button>))}</div>)}</div>);
}
