"use client";
import { motion } from "framer-motion";
type Props = { className?: string; stroke?: string; strokeWidth?: number; animateDraw?: boolean; };
export function Filigrana({ className = "", stroke = "var(--golden)", strokeWidth = 1.2, animateDraw = true }: Props) {
  return (<div className={`flex items-center justify-center gap-4 my-6 ${className}`}><motion.svg width="120" height="20" viewBox="0 0 120 20" fill="none" aria-hidden="true" className="flex-shrink-0" {...(animateDraw ? { initial: { pathLength: 0, opacity: 1 }, whileInView: { pathLength: 1, opacity: 1 }, viewport: { once: true, amount: 0.6 }, transition: { duration: 1.8, ease: "easeInOut" } } : {})}><motion.line x1="0" y1="10" x2="48" y2="10" stroke={stroke} strokeWidth={strokeWidth} strokeLinecap="round" {...(animateDraw ? { initial: { pathLength: 0 }, whileInView: { pathLength: 1 }, viewport: { once: true }, transition: { duration: 1.2 } } : {})} /><motion.path d="M 60 10 m-1 0 a 1 1 0 1 1 2 0 a 3 3 0 1 1 -6 0 a 5 5 0 1 1 10 0 a 7 7 0 1 1 -14 0" stroke={stroke} strokeWidth={strokeWidth * 1.1} strokeLinecap="round" fill="none" {...(animateDraw ? { initial: { pathLength: 0 }, whileInView: { pathLength: 1 }, viewport: { once: true }, transition: { duration: 1.8, delay: 0.3 } } : {})} /><motion.circle cx="60" cy="10" r="0.8" fill={stroke} /><motion.line x1="72" y1="10" x2="120" y2="10" stroke={stroke} strokeWidth={strokeWidth} strokeLinecap="round" {...(animateDraw ? { initial: { pathLength: 0 }, whileInView: { pathLength: 1 }, viewport: { once: true }, transition: { duration: 1.2, delay: 0.2 } } : {})} /></motion.svg></div>);
}
export function RiverSpine({ className = "", stroke = "var(--sage)", strokeWidth = 1.5 }: Props) {
  return (<div className={`relative ${className}`} aria-hidden="true"><svg width="100%" height="100%" viewBox="0 0 40 600" preserveAspectRatio="none" fill="none" className="absolute inset-0"><motion.path d="M 20 0 Q 24 100 20 200 Q 16 300 20 400 Q 24 500 20 600" stroke={stroke} strokeWidth={strokeWidth} strokeLinecap="round" fill="none" initial={{ pathLength: 0 }} whileInView={{ pathLength: 1 }} viewport={{ once: true }} transition={{ duration: 2.5, ease: "easeInOut" }} /></svg><motion.div className="absolute left-1/2 -translate-x-1/2" style={{ top: 0 }} animate={{ top: ["0%", "100%"] }} transition={{ duration: 30, ease: "linear", repeat: Infinity }}><svg width="32" height="20" viewBox="0 0 32 20" fill="none"><path d="M 4 14 Q 6 18 16 18 Q 26 18 28 14 L 24 14 Q 16 16 8 14 Z" fill="var(--terracotta)" stroke="var(--charcoal)" strokeWidth="0.8" /><line x1="16" y1="14" x2="16" y2="2" stroke="var(--charcoal)" strokeWidth="0.8" /><path d="M 16 3 L 22 8 L 16 10 Z" fill="var(--cream)" stroke="var(--charcoal)" strokeWidth="0.5" /><circle cx="16" cy="2" r="1" fill="var(--golden)" /></svg></motion.div></div>);
}
