"use client";
import { motion } from "framer-motion";
import { useState } from "react";
import { RockingChair } from "./illustrations/RockingChair";
import { HouseFacade } from "./illustrations/HouseFacade";
import { Filigrana } from "./Filigrana";
import { useI18n } from "./I18n";
const ROOMS = [{ id: "r1", image: "/room-twin.png", alt: "Habitación doble", capacity: { es: "2 personas · 2 camas", en: "2 guests · 2 beds" }, desc: { es: "Dos camas, ventilador de techo, ventana con postigos. Fresca y muy limpia.", en: "Two beds, ceiling fan, window with shutters. Cool and very clean." } }, { id: "r2", image: "/room-triple.png", alt: "Habitación triple", capacity: { es: "3 personas · 3 camas", en: "3 guests · 3 beds" }, desc: { es: "Una doble y dos individuales. Pa' familias chiquitas o tres amigos.", en: "One double and two singles. For small families or three friends." } }, { id: "r3", image: "/room-twin-amenities.png", alt: "Habitación con baño privado", capacity: { es: "2 personas · baño privado", en: "2 guests · private bath" }, desc: { es: "Toallas dobladas con cariño, amenities de cortesía, aire acondicionado.", en: "Towels folded with care, courtesy amenities, air conditioning." } }];
const ZOOM = [{ id: "door", emoji: "🚪", title: { es: "La puerta principal", en: "The front door" }, desc: { es: "Cruzás el umbral. La casa huele a café y a patio recién regado. Bienvenido.", en: "You cross the threshold. The house smells of coffee and a freshly watered patio. Welcome." }, photo: "/hotel-exterior-day.png", photoAlt: "Fachada de Casa Mónica" }, { id: "window-left", emoji: "🪟", title: { es: "La ventana de Fredy", en: "Fredy's window" }, desc: { es: "Da al callejón de la Albarrada. Desde aquí se escuchan los badajos de Santa Bárbara al atardecer.", en: "Faces the Albarrada alley. From here you hear Santa Bárbara's bells at dusk." }, photo: "/room-twin.png", photoAlt: "Habitación doble" }, { id: "window-right", emoji: "🪟", title: { es: "La ventana de Mónica", en: "Mónica's window" }, desc: { es: "Da al patio interior. Aquí cuelga la hamaca donde Mónica mece a Melissa cuando llueve.", en: "Faces the interior patio. Here hangs the hammock where Mónica rocks Melissa when it rains." }, photo: "/room-twin-amenities.png", photoAlt: "Habitación con baño" }, { id: "balcony", emoji: "🌿", title: { es: "El balcón", en: "The balcony" }, desc: { es: "Bougainvillea trepando por la reja de hierro. Es donde los huéspedes se sientan a tomar el fresco después de la siesta.", en: "Bougainvillea climbing the iron railing. Where guests sit to enjoy the cool air after a siesta." }, photo: "/mompox-patio-sunset-real.jpg", photoAlt: "Patio de Casa Mónica al atardecer" }];
export function House() {
  const { t, lang } = useI18n();
  const [zoomed, setZoomed] = useState<string | null>(null);
  const zt = ZOOM.find(z => z.id === zoomed);
  return (
    <section id="casa" className="bg-cal py-20 sm:py-28 relative overflow-hidden">
      <div className="relative max-w-7xl mx-auto px-6 sm:px-8">
        <motion.div className="text-center mb-12" initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.7, ease: [0.34, 1.56, 0.64, 1] }}>
          <div className="flex items-center justify-center gap-6 mb-3"><div className="block w-12 h-12 sm:w-16 sm:h-16"><RockingChair color="var(--terracotta)" animateDraw /></div><div><div className="eyebrow">{t("house.eyebrow")}</div><h2 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[var(--charcoal)] leading-[1.1] font-light">{t("house.title1")} <em className="text-[var(--terracotta)] not-italic font-medium">{t("house.title2")}</em></h2></div><div className="block w-12 h-12 sm:w-16 sm:h-16"><RockingChair color="var(--sage)" animateDraw /></div></div>
          <p className="font-script text-2xl text-[var(--charcoal)]/75 mt-3">{t("house.subtitle")}</p>
          <Filigrana />
        </motion.div>
        <motion.div className="max-w-3xl mx-auto min-h-[280px] sm:min-h-[28rem] mb-12 relative" initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, amount: 0.3 }} transition={{ duration: 1.2 }}><HouseFacade animateDraw onZoom={setZoomed} /></motion.div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
          {ROOMS.map((room, i) => (<motion.article key={room.id} className="magnetic-target hover-spring" style={{ rotate: i % 2 === 0 ? "-1.5deg" : "1.5deg" }} initial={{ opacity: 0, y: 40, rotate: i % 2 === 0 ? -6 : 6 }} whileInView={{ opacity: 1, y: 0, rotate: i % 2 === 0 ? -1.5 : 1.5 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.7, delay: i * 0.12, ease: [0.34, 1.56, 0.64, 1] }}><div className="bg-[var(--cream)] rounded-2xl overflow-hidden shadow-lg border-2 border-[var(--charcoal)]/10"><div className="relative"><img src={room.image} alt={room.alt} className="w-full aspect-[4/3] object-cover" /><div className="absolute top-3 right-3 bg-[var(--terracotta)] text-[var(--cream)] text-xs font-medium px-3 py-1.5 rounded-full shadow-md">{room.capacity[lang]}</div></div><div className="p-5"><p className="font-serif italic text-sm text-[var(--charcoal)] leading-snug mb-3">{room.desc[lang]}</p><div className="flex items-center gap-2 text-xs text-[var(--terracotta)] font-medium"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 12l2 2 4-4" strokeLinecap="round" strokeLinejoin="round" /><circle cx="12" cy="12" r="10" /></svg><span className="font-sans tracking-[0.1em] uppercase">{t("house.features")}</span></div></div></div></motion.article>))}
        </div>
        <motion.p className="mt-12 text-center font-script text-2xl text-[var(--charcoal)]/75 max-w-2xl mx-auto" initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.9 }}>{t("house.closing")}</motion.p>
      </div>
      {zoomed && zt && (<motion.div className="fixed inset-0 z-[150] bg-[var(--charcoal)]/92 backdrop-blur-md flex items-center justify-center p-4 sm:p-8" initial={{ opacity: 0 }} animate={{ opacity: 1 }} onClick={() => setZoomed(null)}><motion.div className="bg-[var(--cream)] rounded-3xl shadow-2xl max-w-2xl w-full overflow-hidden border-2 border-[var(--terracotta)]" onClick={(e) => e.stopPropagation()} initial={{ scale: 0.4, opacity: 0, rotate: -3 }} animate={{ scale: 1, opacity: 1, rotate: 0 }} transition={{ duration: 0.8, ease: [0.34, 1.56, 0.64, 1] }}><div className="relative aspect-[4/3] overflow-hidden"><motion.img src={zt.photo} alt={zt.photoAlt} className="w-full h-full object-cover" initial={{ scale: 1.4 }} animate={{ scale: 1 }} transition={{ duration: 4, ease: "easeOut" }} /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[var(--charcoal)]/85 to-transparent p-4 sm:p-6"><div className="flex items-center gap-2 mb-1"><span className="text-2xl">{zt.emoji}</span><span className="eyebrow text-[var(--golden)]">{t("house.zoomLabel")}</span></div><h3 className="font-script text-3xl text-[var(--cream)]">{zt.title[lang]}</h3></div><button onClick={() => setZoomed(null)} className="absolute top-3 right-3 w-10 h-10 rounded-full bg-[var(--charcoal)]/40 hover:bg-[var(--charcoal)]/60 backdrop-blur-md flex items-center justify-center transition-colors text-xl text-[var(--cream)]" aria-label="Cerrar">✕</button></div><div className="p-5 sm:p-6 bg-[var(--cream)]"><p className="font-serif italic text-sm sm:text-base text-[var(--charcoal)]/85 leading-relaxed text-center">{zt.desc[lang]}</p></div></motion.div></motion.div>)}
    </section>
  );
}
