"use client";
import { createContext, useContext, useEffect, useState } from "react";
export type Lang = "es" | "en";
type I18nContext = { lang: Lang; setLang: (l: Lang) => void; t: (key: string) => string; };
const Dict: Record<string, { es: string; en: string }> = {
  "nav.casa": { es: "La Casa", en: "The House" }, "nav.galeria": { es: "Galería", en: "Gallery" }, "nav.rio": { es: "El Río", en: "The River" }, "nav.familia": { es: "La Familia", en: "The Family" }, "nav.cosas-hacer": { es: "Cosas que hacer", en: "Things to do" }, "nav.cosas-comer": { es: "Comer", en: "Eat" }, "nav.como-llegar": { es: "Cómo llegar", en: "Getting here" }, "nav.diccionario": { es: "Diccionario", en: "Dictionary" }, "nav.reserva": { es: "Reserva", en: "Book" },
  "hero.h1.line1": { es: "Siéntete", en: "Feel" }, "hero.h1.line2": { es: "como en", en: "at" }, "hero.h1.line3": { es: "casa.", en: "home." },
  "hero.subtitle": { es: "Una familia momposina. 14 habitaciones climatizadas. Una mecedora que te espera en el portal. A 100 pasos del río Magdalena. Y un WhatsApp que lo contestamos nosotros, ¡pues qué vaina!", en: "A momposina family. 14 air-conditioned rooms. A rocking chair waiting on the porch. 100 steps from the Magdalena. And a WhatsApp we answer ourselves!" },
  "hero.body": { es: "Acá no hay recepción con mostrador, ni uniformes. Hay una puerta que se abre, una conversación sobre qué visitar hoy, y un casabito que comprás en la esquina, por si tenías ganas de algo dulce. Como en casa de la abuela, pero con aire acondicionado.", en: "There's no reception desk here, no uniforms. Just a door that opens, a conversation about what to visit today, and a casabito you buy on the corner. Like at grandma's, but with AC." },
  "hero.cta": { es: "Escríbenos por WhatsApp", en: "Message us on WhatsApp" }, "hero.parking": { es: "Parqueadero gratis", en: "Free parking" }, "hero.river": { es: "A 100 pasos del río", en: "100 steps from the river" }, "hero.unesco": { es: "Mompox · UNESCO 1995", en: "Mompox · UNESCO 1995" }, "hero.note": { es: "te esperamos en el portal", en: "we're waiting on the porch" }, "hero.noteSign": { es: "— Fredy & Mónica", en: "— Fredy & Mónica" },
  "house.eyebrow": { es: "La casa", en: "The house" }, "house.title1": { es: "14 habitaciones,", en: "14 rooms," }, "house.title2": { es: "todas con aire", en: "all with AC" }, "house.subtitle": { es: "— acá te recibimos con aire, limpieza y trato de casa. Tocá las ventanas para ver qué hay adentro.", en: "— we welcome you with AC, cleanliness and family treatment. Click the windows to see what's inside." }, "house.closing": { es: "Tenemos 14 habitaciones en total — todas climatizadas, todas sencillas, todas limpias. Pregúntale a Fredy cuál te conviene más.", en: "We have 14 rooms in total — all air-conditioned, all simple, all clean. Ask Fredy which suits you best." }, "house.features": { es: "Aire · Limpieza diaria", en: "AC · Daily housekeeping" }, "house.zoomLabel": { es: "Adentro de la casa", en: "Inside the house" }, "house.doorTitle": { es: "La puerta principal", en: "The front door" }, "house.doorDesc": { es: "Cruzás el umbral. La casa huele a café y a patio recién regado. Bienvenido.", en: "You cross the threshold. The house smells of coffee and a freshly watered patio. Welcome." }, "house.windowFTitle": { es: "La ventana de Fredy", en: "Fredy's window" }, "house.windowFDesc": { es: "Da al callejón de la Albarrada. Desde aquí se escuchan los badajos de Santa Bárbara al atardecer.", en: "Faces the Albarrada alley. From here you hear Santa Bárbara's bells at dusk." }, "house.windowMTitle": { es: "La ventana de Mónica", en: "Mónica's window" }, "house.windowMDesc": { es: "Da al patio interior. Aquí cuelga la hamaca donde Mónica mece a Melissa cuando llueve.", en: "Faces the interior patio. Here hangs the hammock where Mónica rocks Melissa when it rains." }, "house.balconyTitle": { es: "El balcón", en: "The balcony" }, "house.balconyDesc": { es: "Bougainvillea trepando por la reja de hierro. Es donde los huéspedes se sientan a tomar el fresco después de la siesta.", en: "Bougainvillea climbing the iron railing. Where guests sit to enjoy the cool air after a siesta." },
  "gallery.eyebrow": { es: "La casa en fotos", en: "The house in photos" }, "gallery.title1": { es: "Un paseo por", en: "A stroll through" }, "gallery.title2": { es: "Mompox", en: "Mompox" }, "gallery.subtitle": { es: "— el pueblo, la casa, el río, la familia. Pasa el mouse para pausar, toca para verla grande.", en: "— the town, the house, the river, the family. Hover to pause, click to see it large." }, "gallery.closing": { es: "Mompox no se pasa — Mompox se llega. Y una vez llegas, hay todo esto.", en: "You don't pass through Mompox — you arrive at Mompox. And once you arrive, there's all this." },
  "river.eyebrow": { es: "El río", en: "The river" }, "river.title": { es: "Mompox no se pasa — Mompox se llega.", en: "You don't pass through Mompox — you arrive at Mompox." }, "river.subtitle": { es: "— y una vez llegas, hay todo esto.", en: "— and once you arrive, there's all this." }, "river.ceiba": { es: "La ceiba centenaria", en: "The centuries-old ceiba" }, "river.ceibaDesc": { es: "Cien años dando sombra al parque. Si le hablas, contesta.", en: "A hundred years giving shade to the park. If you speak to it, it answers." }, "river.champan": { es: "El champán", en: "The champán" }, "river.champanDesc": { es: "Embarcación de madera con techo de palma. NO la bebida.", en: "Wooden boat with palm-leaf roof. NOT the drink." }, "river.boga": { es: "El boga", en: "The boga" }, "river.bogaDesc": { es: "El remero del Magdalena. Profesión ancestral que sobrevive en Mompox.", en: "The oarsman of the Magdalena. Ancestral profession that survives in Mompox." }, "river.quote": { es: "«Mompox, tierra de Dios, donde se acuesta uno y amanecen dos.»", en: "\"Mompox, land of God, where one lies down and two wake up.\"" }, "river.quoteAttr": { es: "— refrán momposino", en: "— momposino saying" },
  "family.eyebrow": { es: "La familia", en: "The family" }, "family.title1": { es: "Los que", en: "The ones" }, "family.title2": { es: "te van a recibir", en: "who'll welcome you" }, "family.subtitle": { es: "— aquí no hay recepción. Hay familia solamente.", en: "— there's no reception here. Just family." },
  "todo.eyebrow": { es: "Cosas que hacer", en: "Things to do" }, "todo.title1": { es: "6 planes para", en: "6 plans to" }, "todo.title2": { es: "no aburrirte", en: "not get bored" }, "todo.subtitle": { es: "— todos a pie o en lancha. Pregúntale a Fredy, él te los consigue.", en: "— all on foot or by boat. Ask Fredy, he'll arrange them." },
  "eat.eyebrow": { es: "Cosas para comer", en: "Things to eat" }, "eat.title1": { es: "La comida", en: "The food" }, "eat.title2": { es: "momposina", en: "of Mompox" }, "eat.subtitle": { es: "— la base de todo es el río, el maíz, y el corozo. Ven con hambre.", en: "— the base of everything is the river, corn, and corozo. Come hungry." }, "eat.closing": { es: "Si querés casabitos recién hechos, te decimos dónde conseguirlos en Mompox — los hace doña Carmen en la Calle del Comercio, ¡pues qué vaina tan rica!", en: "If you want fresh casabitos, we'll tell you where to find them — doña Carmen makes them on Calle del Comercio. So good!" },
  "llegar.eyebrow": { es: "Cómo llegar", en: "How to get here" }, "llegar.title1": { es: "Llegar a", en: "Getting to" }, "llegar.title2": { es: "Mompox", en: "Mompox" }, "llegar.subtitle": { es: "— no es fácil, pero vale la pena. Te esperamos adonde llegues.", en: "— it's not easy, but worth it. We'll meet you wherever you arrive." }, "llegar.address": { es: "La dirección", en: "The address" }, "llegar.addressLine": { es: "Calle 14 #2 74", en: "Calle 14 #2 74" }, "llegar.addressDesc": { es: "Barrio Santa Bárbara, entre la Calle del Medio y la Calle de Atrás. A 100 pasos de la Albarrada y del río Magdalena.", en: "Santa Bárbara neighborhood, between Calle del Medio and Calle de Atrás. 100 steps from the Albarrada and the Magdalena River." }, "llegar.closing": { es: "Si te perdés o tenés dudas, escribinos por WhatsApp. Fredy te explica la ruta, te espera en el terminal o va a buscarte si llegas muy noche.", en: "If you get lost or have questions, message us on WhatsApp. Fredy will explain the route, meet you at the terminal, or pick you up if you arrive late." },
  "dict.eyebrow": { es: "Diccionario momposino", en: "Momposino dictionary" }, "dict.title1": { es: "Palabras que", en: "Words you'll" }, "dict.title2": { es: "vas a aprender", en: "actually learn" }, "dict.subtitle": { es: "— porque acá hablamos distinto, pues qué. Tocá cualquier palabra para verla.", en: "— because here we speak differently. Click any word to see it." }, "dict.example": { es: "Ejemplo", en: "Example" }, "dict.signoff": { es: "— y Mónica te lo explica mejor que nadie.", en: "— and Mónica will explain it better than anyone." }, "dict.filterAll": { es: "Todo", en: "All" },
  "reserve.eyebrow": { es: "El último capítulo", en: "The last chapter" }, "reserve.title1": { es: "Reservá tu capítulo.", en: "Book your chapter." }, "reserve.title2": { es: "Te esperamos en casa.", en: "We're waiting for you at home." }, "reserve.body": { es: "«Vivimos acá. Te estás quedando en nuestra casa.» Mónica contesta ella misma. Sin intermediarios, sin formulario de disponibilidad — puro hablar caribeño, despacio, sin apuros.", en: "\"We live here. You're staying in our home.\" Mónica answers herself. No middlemen, no availability form — just Caribbean conversation, slow, no rushing." }, "reserve.cta": { es: "Escríbenos por WhatsApp", en: "Message us on WhatsApp" }, "reserve.goodnight": { es: "Buenas noches. Siéntete como en casa.", en: "Goodnight. Feel at home." }, "reserve.goodnightSub": { es: "— que el Magdalena te meza, que los campanarios te canten, que amanezcas dos.", en: "— may the Magdalena rock you, may the bell towers sing to you, may you wake up as two." },
  "footer.closing": { es: "Una casa de familia en el corazón colonial de Mompox — la isla que Bolívar llamó la cuna de su gloria, y que García Márquez soñó pero no existía. Pero Mompox sí existe. Y dentro de ella, una casa.", en: "A family home in the colonial heart of Mompox — the island Bolívar called the cradle of his glory, and that García Márquez dreamed but didn't exist. But Mompox does exist. And inside it, a home." },
};
const I18nCtx = createContext<I18nContext>({ lang: "es", setLang: () => {}, t: (k) => Dict[k]?.es ?? k });
export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("es");
  useEffect(() => { try { const s = window.localStorage.getItem("cm-lang"); if (s === "es" || s === "en") setLangState(s); } catch {} }, []);
  const setLang = (l: Lang) => { setLangState(l); try { window.localStorage.setItem("cm-lang", l); } catch {} };
  const t = (key: string) => Dict[key]?.[lang] ?? key;
  return <I18nCtx.Provider value={{ lang, setLang, t }}>{children}</I18nCtx.Provider>;
}
export function useI18n() { return useContext(I18nCtx); }
