"use client";
import { motion } from "framer-motion";
import { useI18n } from "./I18n";
import { Filigrana } from "./Filigrana";
const DISHES = [{ id: "bocachico", emoji: "🐟", name: { es: "Bocachico", en: "Bocachico" }, img: "/food-bocachico.jpg", desc: { es: "El pescado del Magdalena. Asado al ajillo, en sudado o frito.", en: "The Magdalena river fish. Grilled with garlic, in stew or fried." }, where: { es: "Cualquier restaurante del centro", en: "Any restaurant in town" }, img: "/momposina-food.png" }, { id: "arepa-huevo", emoji: "🥚", name: { es: "Arepa 'e huevo", en: "Egg arepa" }, img: "/food-arepa-huevo.jpg", desc: { es: "Arepa de maíz frita rellena de huevo entero. Patrimonio del Caribe.", en: "Fried corn arepa stuffed with a whole egg. Caribbean heritage." }, where: { es: "Calle del Comercio", en: "Calle del Comercio" } }, { id: "casabito", emoji: "🥮", name: { es: "Casabito", en: "Casabito" }, desc: { es: "Tortillita de yuca, queso, coco y azúcar. Los hace doña Carmen en la Calle del Comercio.", en: "Little pancake of cassava, cheese, coconut and sugar. Doña Carmen makes them." }, where: { es: "Calle del Comercio", en: "Calle del Comercio" } }, { id: "corozo", emoji: "🍒", name: { es: "Vino de corozo", en: "Corozo wine" }, desc: { es: "El corozo es el fruto de una palma del Caribe. Vino dulce, color rubí, servido frío.", en: "Corozo is the fruit of a Caribbean palm. Sweet wine, ruby color, served cold." }, where: { es: "Catas en el centro histórico", en: "Tastings in the historic center" }, img: "/corozo-fruit.png" }, { id: "queso-capa", emoji: "🧀", name: { es: "Queso de capa", en: "Layered cheese" }, img: "/filigree-artisan-ai.jpg", desc: { es: "Queso hilado, elástico, más de 100 años de tradición artesanal en Mompox.", en: "Stretched, elastic cheese, over 100 years of artisanal tradition." }, where: { es: "Mercado municipal", en: "Municipal market" } }, { id: "posta-negra", emoji: "🍲", name: { es: "Posta negra", en: "Black posta" }, img: "/food-posta-negra.jpg", desc: { es: "Carne guisada en salsa oscura de panela y especias. Única de Mompox.", en: "Beef stewed in dark panela and spice sauce. Unique to Mompox." }, where: { es: "Restaurante Montecristo", en: "Montecristo restaurant" } }];
export function ThingsToEat() {
  const { t, lang } = useI18n();
  return (
    <section id="cosas-comer" className="py-20 sm:py-28 relative overflow-hidden" style={{ background: "linear-gradient(135deg, #2a3a25 0%, #1a2820 100%)" }}>
      <div className="relative max-w-7xl mx-auto px-6 sm:px-8">
        <motion.div className="text-center mb-12" initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.7, ease: [0.34, 1.56, 0.64, 1] }}>
          <div className="eyebrow text-[var(--golden)] mb-3">{t("eat.eyebrow")}</div>
          <h2 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[var(--golden)] leading-[1.1] font-light">{t("eat.title1")} <em className="text-[var(--terracotta)] not-italic font-medium">{t("eat.title2")}</em></h2>
          <p className="font-script text-2xl text-[var(--cream)]/70 mt-3">{t("eat.subtitle")}</p>
          <Filigrana />
        </motion.div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
          {DISHES.map((dish, i) => (<motion.article key={dish.id} className="magnetic-target hover-spring bg-[var(--cream)]/10 backdrop-blur-sm rounded-xl overflow-hidden border border-[var(--golden)]/30" style={{ rotate: i % 3 === 0 ? "1deg" : i % 3 === 1 ? "-0.5deg" : "-1deg" }} initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.7, delay: (i % 3) * 0.1, ease: [0.34, 1.56, 0.64, 1] }}>{dish.img && (<div className="relative aspect-[4/3] overflow-hidden"><img src={dish.img} alt={dish.name[lang]} loading="lazy" className="w-full h-full object-cover transition-transform duration-700 hover:scale-105" /><div className="absolute top-3 right-3 w-10 h-10 rounded-full flex items-center justify-center text-lg shadow-md ring-2 ring-[var(--cream)] bg-[var(--golden)]">{dish.emoji}</div></div>)}<div className="p-5"><div className="flex items-baseline justify-between gap-2 mb-2"><h3 className="font-serif text-lg text-[var(--cream)] leading-tight">{dish.name[lang]}</h3>{!dish.img && <span className="text-2xl">{dish.emoji}</span>}</div><p className="font-sans text-sm text-[var(--cream)]/75 leading-relaxed mb-3">{dish.desc[lang]}</p><div className="flex items-start gap-2 text-xs text-[var(--golden)] font-medium pt-3 border-t border-[var(--golden)]/20"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="flex-shrink-0 mt-0.5"><path d="M12 2C8 2 5 5 5 9c0 5 7 13 7 13s7-8 7-13c0-4-3-7-7-7z" /></svg><span className="font-sans">{dish.where[lang]}</span></div></div></motion.article>))}
        </div>
        <motion.p className="mt-12 text-center font-script text-2xl text-[var(--cream)]/70 max-w-2xl mx-auto" initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.9 }}>{t("eat.closing")}</motion.p>
      </div>
    </section>
  );
}
