"use client";
import { motion } from "framer-motion";
import { useI18n } from "./I18n";
import { Filigrana } from "./Filigrana";
const EXPERIENCES = [{ id: "santa-barbara", emoji: "🏛️", title: { es: "Caminar las 7 iglesias", en: "Walk the 7 churches" }, desc: { es: "Santa Bárbara, la Concepción, San Agustín — Mompox tiene 7 iglesias coloniales, todas a pie.", en: "Santa Bárbara, Concepción, San Agustín — Mompox has 7 colonial churches, all walkable." }, duration: { es: "2-3 horas", en: "2-3 hours" }, img: "/mompox-santa-barbara-night.jpg" }, { id: "filigrana", emoji: "💍", title: { es: "Taller de filigrana", en: "Filigree workshop" }, desc: { es: "Visitá el taller de los Trespalacios, tres generaciones tejiendo oro en hilo.", en: "Visit the Trespalacios workshop, three generations weaving gold thread." }, duration: { es: "1 hora", en: "1 hour" }, img: "/filigree-artisan.png" }, { id: "champan", emoji: "⛵", title: { es: "Paseo en champán", en: "Champán boat ride" }, desc: { es: "Subí al champán tradicional y navegá por el Magdalena. Caimanes, aves y el río como hace 200 años.", en: "Board the traditional champán and sail the Magdalena. Caimans, birds, the river as it was 200 years ago." }, duration: { es: "3-4 horas", en: "3-4 hours" }, img: "/mompox-river-colonial.jpg" }, { id: "casa-cultural", emoji: "🎨", title: { es: "Casa de la Cultura", en: "House of Culture" }, desc: { es: "Museo de arte religioso en un antiguo convento. Cruz de plata, santos tallados, oro filigrana.", en: "Religious art museum in a former convent. Silver crosses, carved saints, gold filigree." }, duration: { es: "1-2 horas", en: "1-2 hours" }, img: "/casa-cultura-mompox.jpg" }, { id: "mompox-noche", emoji: "🕯️", title: { es: "Caminata nocturna", en: "Night walk" }, desc: { es: "Cuando el sol se mete, Mompox se vuelve otra cosa — faroles, calles vacías, campanas.", en: "When the sun sets, Mompox becomes something else — lanterns, empty streets, bells." }, duration: { es: "1.5 horas", en: "1.5 hours" }, img: "/mompox-street-banners.jpg" }, { id: "cienaga", emoji: "🦅", title: { es: "Ciénaga de Pijiño", en: "Pijiño Swamp" }, desc: { es: "Canales cavados por los Zenú hace siglos. Aves migratorias, garzas, caimanes pequeños.", en: "Channels dug by the Zenú centuries ago. Migratory birds, herons, small caimans." }, duration: { es: "Media jornada", en: "Half day" }, img: "/cienaga-pijino.png" }];
export function ThingsToDo() {
  const { t, lang } = useI18n();
  return (
    <section id="cosas-hacer" className="bg-cal py-20 sm:py-28 relative overflow-hidden">
      <div className="relative max-w-7xl mx-auto px-6 sm:px-8">
        <motion.div className="text-center mb-12" initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.7, ease: [0.34, 1.56, 0.64, 1] }}>
          <div className="eyebrow mb-3">{t("todo.eyebrow")}</div>
          <h2 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[var(--charcoal)] leading-[1.1] font-light">{t("todo.title1")} <em className="text-[var(--terracotta)] not-italic font-medium">{t("todo.title2")}</em></h2>
          <p className="font-script text-2xl text-[var(--charcoal)]/75 mt-3">{t("todo.subtitle")}</p>
          <Filigrana />
        </motion.div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
          {EXPERIENCES.map((exp, i) => (<motion.article key={exp.id} className="magnetic-target hover-spring bg-[var(--cream)] overflow-hidden shadow-md border-2 border-[var(--charcoal)]/10 rounded-l-lg rounded-r-none border-r-0 relative" style={{ rotate: i % 3 === 0 ? "-1deg" : i % 3 === 1 ? "0.5deg" : "1deg" }} initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.7, delay: (i % 3) * 0.1, ease: [0.34, 1.56, 0.64, 1] }}>{exp.img && (<div className="relative aspect-[4/3] overflow-hidden"><img src={exp.img} alt={exp.title[lang]} loading="lazy" className="w-full h-full object-cover transition-transform duration-700 hover:scale-105" /><div className="absolute top-3 left-3 w-10 h-10 rounded-full flex items-center justify-center text-lg shadow-md ring-2 ring-[var(--cream)] bg-[var(--terracotta)]">{exp.emoji}</div></div>)}<div className="absolute top-0 right-0 h-full w-2 border-l-2 border-dashed border-[var(--charcoal)]/20"></div><div className="p-5"><div className="flex items-baseline justify-between gap-2 mb-2"><h3 className="font-serif text-lg text-[var(--charcoal)] leading-tight">{exp.title[lang]}</h3>{!exp.img && <span className="text-2xl">{exp.emoji}</span>}</div><p className="font-sans text-sm text-[var(--charcoal)]/75 leading-relaxed mb-3">{exp.desc[lang]}</p><div className="flex items-center gap-2 text-xs text-[var(--terracotta)] font-medium pt-3 border-t border-[var(--charcoal)]/10"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="12" cy="12" r="10" /><path d="M12 6v6l4 2" strokeLinecap="round" /></svg><span className="font-sans tracking-[0.1em] uppercase">{exp.duration[lang]}</span></div></div></motion.article>))}
        </div>
      </div>
    </section>
  );
}
